import { getRepDb } from "@main/db/db.js";
import { bufferToHex, generateUUIDV7, hexToBuffer } from "@main/db/import/utils.js";
import { cardsTable, collectionTable, decksTable, reviewLogsTable } from "@main/db/schema/repetition/rep.js";
import { eq } from "drizzle-orm";
import { ColConfig } from "../collection/col-service-types.js";
import { toFSRSCard } from "./card-mapper.js";
import { nextHandler, toCard, toCardQueue } from "./card-service-helper.js";
import { CardQueue, CardReviewRating, CardReviewResult, CardState, FSRSCard, FSRSRecordLogItem, ReviewedCardState } from "./card-service-types.js";
import { getFsrsScheduler, toFsrsGrade } from "./card-scheduler.js";
import { PendingLocalUsn } from "@main/sync/helper/usn.js";

type RepTx = Parameters<Parameters<ReturnType<typeof getRepDb>["transaction"]>[0]>[0];
type ReviewCardRow = typeof cardsTable.$inferSelect;
type ReviewDeckRow = Pick<
    typeof decksTable.$inferSelect,
    "config" | "newLearnedToday" | "learnedToday" | "reviewedToday"
>;
type ReviewDeckStats = Pick<ReviewDeckRow, "newLearnedToday" | "learnedToday" | "reviewedToday">;

interface ReviewOutcome {
    /** FSRS card after applying the selected rating. */
    nextCard: FSRSCard;
    /** Queue derived from the next FSRS card state. */
    nextQueue: CardQueue;
    /** Shared update timestamp in milliseconds. */
    updatedAt: number;
    /** FSRS record log item generated by the scheduler. */
    recordLogItem: FSRSRecordLogItem;
}

/**
 * Apply one FSRS review result, update the card, deck counters, and review log.
 */
export async function reviewCard(cardId: string, rating: CardReviewRating, duration: number): Promise<CardReviewResult> {
    const db = getRepDb();
    return db.transaction((tx) => {
        const cardRow = tx.select()
            .from(cardsTable)
            .where(eq(cardsTable.id, hexToBuffer(cardId)))
            .get();
        if (!cardRow) {
            return { state: "card-not-found" };
        }

        const deckRow = getReviewDeckInTx(tx, cardRow.deckId);
        if (!deckRow) {
            return { state: "deck-not-found" };
        }

        const collectionConfig = getCollectionConfigInTx(tx);
        const outcome = buildReviewOutcome(cardRow, deckRow, collectionConfig, rating);
        const nextDeckStats = resolveDeckReviewStats(deckRow, cardRow);

        updateReviewedCardInTx(tx, cardRow, outcome);
        updateReviewedDeckStatsInTx(tx, cardRow.deckId, nextDeckStats, outcome.updatedAt);
        insertReviewLogInTx(tx, cardRow.id, outcome.recordLogItem, duration);

        return {
            state: "success",
            card: toReviewedCardState(cardRow, outcome),
        };
    });
}

/**
 * Read deck data needed to review one card inside the current transaction.
 */
function getReviewDeckInTx(tx: RepTx, deckId: Buffer): ReviewDeckRow | undefined {
    return tx.select({
        config: decksTable.config,
        newLearnedToday: decksTable.newLearnedToday,
        learnedToday: decksTable.learnedToday,
        reviewedToday: decksTable.reviewedToday,
    })
        .from(decksTable)
        .where(eq(decksTable.id, deckId))
        .get();
}

/**
 * Read the collection config inside the current transaction.
 */
function getCollectionConfigInTx(tx: RepTx): ColConfig {
    const collectionRecord = tx.select({
        config: collectionTable.config,
    })
        .from(collectionTable)
        .get();
    if (!collectionRecord) {
        throw new Error("Collection config not found.");
    }
    return collectionRecord.config;
}

/**
 * Build the next card scheduling result and review log data for one rating.
 */
function buildReviewOutcome(
    cardRow: ReviewCardRow,
    deckRow: ReviewDeckRow,
    collectionConfig: ColConfig,
    rating: CardReviewRating,
): ReviewOutcome {
    /** Review timestamp shared by card and review-log updates. */
    const now = new Date();
    const deckId = bufferToHex(cardRow.deckId);
    const srcCard = toCard(toFSRSCard(cardRow), collectionConfig);
    const scheduler = getFsrsScheduler(deckId, deckRow.config.fsrsParams);
    
    const recordLogItem = scheduler.next(srcCard, now, toFsrsGrade(rating), nextHandler);
    const nextCard = recordLogItem.card;

    return {
        nextCard,
        nextQueue: toCardQueue(nextCard),
        updatedAt: now.getTime(),
        recordLogItem,
    };
}

/**
 * Persist the reviewed card's next scheduling state inside the current transaction.
 */
function updateReviewedCardInTx(tx: RepTx, cardRow: ReviewCardRow, outcome: ReviewOutcome): void {
    const nextCard = outcome.nextCard;
    tx.update(cardsTable)
        .set({
            usn: PendingLocalUsn,
            updatedAt: outcome.updatedAt,
            difficulty: nextCard.difficulty,
            stability: nextCard.stability,
            scheduledDays: nextCard.scheduledDays,
            due: outcome.nextCard.due.getTime(),
            lastReview: nextCard.lastReview ? nextCard.lastReview.getTime() : null,
            lapses: nextCard.lapses,
            learningSteps: nextCard.learningSteps,
            repetitions: nextCard.repetitions,
            state: nextCard.state,
            queue: outcome.nextQueue,
        })
        .where(eq(cardsTable.id, cardRow.id))
        .run();
}

/**
 * Persist deck daily counters affected by one review inside the current transaction.
 */
function updateReviewedDeckStatsInTx(
    tx: RepTx,
    deckId: Buffer,
    nextDeckStats: ReviewDeckStats,
    updatedAt: number,
): void {
    tx.update(decksTable)
        .set({
            usn: PendingLocalUsn,
            updatedAt,
            newLearnedToday: nextDeckStats.newLearnedToday,
            learnedToday: nextDeckStats.learnedToday,
            reviewedToday: nextDeckStats.reviewedToday,
        })
        .where(eq(decksTable.id, deckId))
        .run();
}

/**
 * Append one immutable review log row inside the current transaction.
 */
function insertReviewLogInTx(
    tx: RepTx,
    cardId: Buffer,
    recordLogItem: ReviewOutcome["recordLogItem"],
    duration: number,
): void {
    tx.insert(reviewLogsTable)
        .values({
            id: generateUUIDV7(),
            cardId,
            usn: PendingLocalUsn,
            reviewTime: recordLogItem.log.reviewTime.getTime(),
            scheduledDays: recordLogItem.log.scheduledDays,
            rating: recordLogItem.log.rating,
            difficulty: recordLogItem.log.difficulty,
            stability: recordLogItem.log.stability,
            learningSteps: recordLogItem.log.learningSteps,
            state: recordLogItem.log.state,
            duration,
        })
        .run();
}

/**
 * Convert the reviewed card update result to the renderer-facing state summary.
 */
function toReviewedCardState(cardRow: ReviewCardRow, outcome: ReviewOutcome): ReviewedCardState {
    return {
        cardId: bufferToHex(cardRow.id),
        queue: outcome.nextQueue,
        state: outcome.nextCard.state as CardState,
        due: outcome.nextCard.due.getTime(),
    };
}

/**
 * Resolve persisted deck daily counters after one card review.
 */
function resolveDeckReviewStats(deck: ReviewDeckStats, sourceCard: ReviewCardRow): ReviewDeckStats {
    /** Next persisted deck counters after applying the review action. */
    const nextStats = {
        newLearnedToday: deck.newLearnedToday,
        learnedToday: deck.learnedToday,
        reviewedToday: deck.reviewedToday,
    };

    if (sourceCard.queue === CardQueue.NEW) {
        nextStats.newLearnedToday += 1;
        nextStats.learnedToday += 1;
        return nextStats;
    }

    if (sourceCard.queue === CardQueue.LEARNING) {
        nextStats.learnedToday += 1;
        return nextStats;
    }

    if (sourceCard.queue === CardQueue.REVIEW) {
        nextStats.reviewedToday += 1;
    }

    return nextStats;
}
